// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeriTabaniProjesi.Context;

#nullable disable

namespace VeriTabaniProjesi.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeriTabaniProjesi.Models.Course", b =>
                {
                    b.Property<int>("course_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_ID"));

                    b.Property<string>("course_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("credits")
                        .HasColumnType("int");

                    b.HasKey("course_ID");

                    b.HasIndex("course_name")
                        .IsUnique();

                    b.ToTable("course");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.Instructor", b =>
                {
                    b.Property<int>("instructor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instructor_ID"));

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("instructor_ID");

                    b.ToTable("instructor");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.Student", b =>
                {
                    b.Property<int>("student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_ID"));

                    b.Property<string>("courses_selected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_ID");

                    b.ToTable("student");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.StudentCourse", b =>
                {
                    b.Property<int>("student_ID")
                        .HasColumnType("int");

                    b.Property<int>("course_ID")
                        .HasColumnType("int");

                    b.HasKey("student_ID", "course_ID");

                    b.HasIndex("course_ID");

                    b.ToTable("studentcourse");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.StudentCourse", b =>
                {
                    b.HasOne("VeriTabaniProjesi.Models.Course", "course")
                        .WithMany("studentcourses")
                        .HasForeignKey("course_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeriTabaniProjesi.Models.Student", "student")
                        .WithMany("studentcourses")
                        .HasForeignKey("student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.Course", b =>
                {
                    b.Navigation("studentcourses");
                });

            modelBuilder.Entity("VeriTabaniProjesi.Models.Student", b =>
                {
                    b.Navigation("studentcourses");
                });
#pragma warning restore 612, 618
        }
    }
}
